### ISSUE TITLE
can not run 'pip install -e .' in infinistore directory

### ISSUE THREAD

**Issue by CharlesJhonson** [bytedance/InfiniStore#76]
when I run 'pip install -e .' in infinistore, some errors as flow:
/home/infiniStore# ls
EADME.md  build_manylinux_wheels.sh  infinistore setup.py  src
/home/infiniStore# pip install -e .

..........(omit)
-o _infinistore.cpython-310-x86_64-linux-gnu.so -L/usr/local/cuda/lib64 -lcudart -luv -libverbs
    rm -rf ../infinistore/_infinistore.cpython-310-x86_64-linux-gnu.so
    cp _infinistore.cpython-310-x86_64-linux-gnu.so ../infinistore/
    error: can't copy 'build/lib.linux-x86_64-cpython-310/infinistore/_infinistore.cpython-310-x86_64-linux-gnu.so': doesn't exist or not a regular file
    developer mode: building shared library
    [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
---------
/home/infiniStore# ls
README.md  build  build_manylinux_wheels.sh  dist  infinistore  infinistore.egg-info  setup.py  src
----
Could someone help me, thank you very much!

**Comment by thesues** [comment]
what's inside directory src?

**Comment by CharlesJhonson** [comment]
`(infiniStore) root@host:/home/infiniStore# ls

README.md  build_manylinux_wheels.sh  infinistore  infinistore.egg-info  setup.py  src
(infiniStore) root@host:/home/infiniStore# ls src/

Makefile                                      ibv_helper.cpp   libinfinistore.cpp              log.cpp      mempool.o                 pybind.cpp
_infinistore.cpython-310-x86_64-linux-gnu.so  ibv_helper.d     libinfinistore.d                log.d        meta_request.fbs          test
allocate_response.fbs                         ibv_helper.h     libinfinistore.h                log.h        meta_request_generated.h  utils.cpp
allocate_response_generated.h                 ibv_helper.o     libinfinistore.o                log.o        protocol.cpp              utils.d
config.h                                      infinistore.cpp  local_meta_generated.h          mempool.cpp  protocol.d                utils.h
get_match_last_index.fbs                      infinistore.d    local_meta_request.fbs          mempool.d    protocol.h                utils.o
get_match_last_index_generated.h              infinistore.o    local_meta_request_generated.h  mempool.h    protocol.o`

**Comment by thesues** [comment]
it seems _infinistore.cpython-310-x86_64-linux-gnu.so is generated. can you manually copy it into infinistore directory? 
![image](https://github.com/user-attachments/assets/dd1af063-feff-4926-af1a-be41d614eaf9)

it should work in this case
